name: MinGW

on:
  pull_request:
  push:
    branches-ignore:
    - coverity_scan
    paths-ignore:
    - '.circleci/**'
    - '.github/actions/spelling/**'
    - 'docs/**'
    - 'packages**'
    - .cirrus.yml
    - .clang-format
    - .gitignore
    - .travis.yml
    - AUTHORS
    - COPYRIGHT
    - ChangeLog.md
    - LICENSE
    - README.md
    - appveyor.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: fetch tags
      run: git fetch --unshallow --tags --prune --force
    - name: configure
      run: cmake  -G "MinGW Makefiles" .
    - name: build
      run: cmake --build .
#    - name: test
#      shell: pwsh
#      run: |
#        & mdbx_test.exe --progress --console=no --pathname=test.db --dont-cleanup-after basic > test.log
#        Get-Content test.log | Select-Object -last 42
#        if ($LastExitCode -ne 0) {
#            throw "Exec: $ErrorMessage"
#        } else {
#            & mdbx_chk.exe -nvv test.db | Tee-Object -file chk.log | Select-Object -last 42
#        }
